# Generated by Django 4.0.4 on 2022-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medadmin', '0002_rename_n_id_medadmin_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medadmin',
            name='email',
            field=models.EmailField(default='mock@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='medadmin',
            name='nid',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='medadmin',
            name='phonenumber',
            field=models.CharField(default='0123456789', max_length=20),
        ),
    ]
