# Generated by Django 4.0.4 on 2022-04-21 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medadmin', '0003_alter_medadmin_email_alter_medadmin_nid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medadmin',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
